import { db } from "@workspace/db";
import { coachesTable, reviewsTable } from "@workspace/db";
import { count } from "drizzle-orm";
import { logger } from "./lib/logger";

const coaches = [
  { userId: "seed_user_1", name: "陳偉雄", sportsCategory: "游泳", location: "沙田", bio: "前香港代表隊游泳選手，擁有15年教學經驗。專注於提升學員的游泳技術及體能，曾訓練多位全港學界賽事冠軍。採用科學化訓練方法，適合各年齡層學員。", trialPrice: "250", regularPrice: "450", packageDetails: "10堂套餐 $3,800", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/1.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_2", name: "李美琪", sportsCategory: "瑜伽", location: "中環", bio: "持國際認可RYT-500瑜伽教練資格，專精陰瑜伽及流瑜伽。在香港及峇里島接受專業訓練，擅長幫助學員紓壓及改善體態。", trialPrice: "200", regularPrice: "380", packageDetails: "月費8堂 $2,600", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/2.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_3", name: "張志明", sportsCategory: "籃球", location: "觀塘", bio: "前香港甲組籃球聯賽球員，擁有FIBA Level 1教練資格。專注青少年籃球培訓，強調基本功訓練及團隊精神，適合初學至進階學員。", trialPrice: "300", regularPrice: "500", packageDetails: "小組班（4人）每位$250/小時", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/3.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_4", name: "黃欣彤", sportsCategory: "網球", location: "西灣河", bio: "ITF認可網球教練，曾代表香港出戰亞洲區賽事。擅長教導初學者掌握正確揮拍技術，並為進階學員提供戰術分析及賽前準備訓練。", trialPrice: "280", regularPrice: "480", packageDetails: "12堂套餐 $4,800", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/4.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_5", name: "吳建國", sportsCategory: "拳擊", location: "旺角", bio: "前香港業餘拳擊總會認可教練，訓練超過300名學員。除技術訓練外，更注重學員的體能與心理素質培養。提供個人及小組訓練。", trialPrice: "200", regularPrice: "400", packageDetails: "8堂套餐 $2,800", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/5.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_6", name: "林曉雯", sportsCategory: "普拉提", location: "銅鑼灣", bio: "STOTT PILATES認證教練，主修墊上及器械普拉提。專注幫助學員改善姿態、核心肌群強化及脊椎健康，特別適合長期坐辦公室人士及產後復原。", trialPrice: "350", regularPrice: "600", packageDetails: "私人堂10次套餐 $5,200", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/6.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_7", name: "鄭家豪", sportsCategory: "足球", location: "元朗", bio: "持有香港足球總會C級教練執照，曾效力本地甲組球隊。專注6至16歲青少年足球訓練，強調技術與運動精神並重，曾帶領學員奪得多個區際賽事獎項。", trialPrice: "220", regularPrice: "420", packageDetails: "小組班（6人）每位$180/小時", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/7.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_8", name: "許嘉慧", sportsCategory: "羽毛球", location: "荃灣", bio: "前香港青年代表羽毛球選手，現為全職教練。擁有香港羽毛球總會認可教練資格，提供個人技術分析及比賽策略訓練，適合各程度學員。", trialPrice: "240", regularPrice: "420", packageDetails: "10堂套餐 $3,600", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/8.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_9", name: "劉俊傑", sportsCategory: "跑步", location: "大埔", bio: "香港馬拉松完成者（個人最佳3小時12分），持有Athletics Hong Kong認可田徑教練資格。專注長跑技術、配速策略及運動傷害預防，適合備戰渣馬或訓練體能人士。", trialPrice: "180", regularPrice: "350", packageDetails: "12週馬拉松備戰計劃 $3,500", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/9.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_10", name: "何雅詩", sportsCategory: "舞蹈", location: "九龍塘", bio: "香港演藝學院舞蹈系畢業，主修芭蕾及現代舞。現任多所國際學校舞蹈老師，提供RAD認可芭蕾考試備考班，亦有中國舞及爵士舞課程。", trialPrice: "280", regularPrice: "480", packageDetails: "考試備考套餐（8堂）$3,200", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/10.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_11", name: "梁偉龍", sportsCategory: "高爾夫球", location: "粉嶺", bio: "PGA認可高爾夫球教練，執教超過12年。提供全面的揮桿分析、3D動作捕捉教學及球場實戰訓練。歡迎完全初學者及有意降低差點的球員。", trialPrice: "500", regularPrice: "800", packageDetails: "私人教學月費套餐（4堂）$2,800", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/11.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_12", name: "蔡慧敏", sportsCategory: "游泳", location: "將軍澳", bio: "香港游泳總會認可教練，專注嬰幼兒及兒童游泳訓練。以耐心及趣味方式幫助小朋友克服對水的恐懼，建立正確游泳技術，安全為首要考慮。", trialPrice: "200", regularPrice: "380", packageDetails: "親子游泳班（10堂）$3,200", ageGroups: ["兒童（12歲以下）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/12.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_13", name: "羅文彬", sportsCategory: "乒乓球", location: "深水埗", bio: "前香港青少年乒乓球代表，現為全職教練。擁有國際乒乓球聯盟認可教練資格，提供個人技術訓練及業餘聯賽備戰指導。", trialPrice: "180", regularPrice: "350", packageDetails: "10堂套餐 $3,000", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/13.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_14", name: "楊曉彤", sportsCategory: "體操", location: "沙田", bio: "前香港體操代表隊成員，現為私人及學校體操教練。提供藝術體操及競技體操訓練，從基礎柔韌訓練到高難度動作分解，循序漸進適合各程度。", trialPrice: "300", regularPrice: "500", packageDetails: "12堂套餐 $5,000", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/14.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_15", name: "曾國強", sportsCategory: "跆拳道", location: "屯門", bio: "ITF跆拳道黑帶三段，持香港跆拳道總會教練資格。提供技術訓練及品格教育並重的課程，專注6至18歲青少年，歡迎備考晉級考試學員。", trialPrice: "200", regularPrice: "380", packageDetails: "晉級備考班（8堂）$2,600", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/15.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_16", name: "鍾雅蘭", sportsCategory: "瑜伽", location: "北角", bio: "Yoga Alliance E-RYT 200認證導師，主修哈他瑜伽及孕婦瑜伽。擅長幫助有肌肉繃緊或關節問題人士以溫和方式改善身體狀況，設有特別課程照顧長者需求。", trialPrice: "180", regularPrice: "350", packageDetails: "月費12堂 $3,600", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/16.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_17", name: "葉子豪", sportsCategory: "田徑", location: "灣仔", bio: "NSCA-CSCS認證體能訓練師，擁有運動科學學士學位。專注功能性訓練、增肌減脂及運動傷害復康。每位學員均設有個人化訓練計劃，配合飲食建議。", trialPrice: "350", regularPrice: "600", packageDetails: "20堂套餐 $10,000（另加體能評估）", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: true, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/17.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_18", name: "馮嘉欣", sportsCategory: "排球", location: "青衣", bio: "曾代表香港女子排球隊出賽亞洲賽事，現為全職教練。擅長接球技術訓練及戰術佈陣分析，歡迎學界球隊及業餘球員參加個人或小組課程。", trialPrice: "220", regularPrice: "400", packageDetails: "小組班（最多6人）每位$180/堂", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/18.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_19", name: "石志遠", sportsCategory: "劍擊", location: "九龍城", bio: "FIE認可劍擊教練，擅長花劍及重劍。曾帶領學員在香港劍擊錦標賽奪獎。提供個人及小組訓練，從零基礎到備戰比賽均可，歡迎家長為子女報讀。", trialPrice: "300", regularPrice: "520", packageDetails: "8堂套餐 $3,600", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/19.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_20", name: "伍詩雅", sportsCategory: "游泳", location: "馬鞍山", bio: "前全港學界游泳冠軍，HKSI認可游泳教練。專注青少年競技游泳訓練，包括四式（自由式、蛙式、背泳、蝶式）技術精進及學界賽事備戰。", trialPrice: "260", regularPrice: "460", packageDetails: "競技訓練計劃（16堂）$6,400", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/20.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_21", name: "江文傑", sportsCategory: "網球", location: "跑馬地", bio: "ITF Level 2教練，執教逾10年。提供成人網球速成課程，以實戰為主要訓練方向。特設晚間及週末班，方便在職人士安排訓練時間。", trialPrice: "300", regularPrice: "520", packageDetails: "成人速成班（8堂）$3,600", ageGroups: ["成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/21.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_22", name: "潘思穎", sportsCategory: "普拉提", location: "太古", bio: "ACE認證私人教練，主修女性體能訓練。專注產後恢復、骨盆底肌訓練及塑形課程。以科學化方法設計訓練計劃，配合體態分析報告，助學員安全有效達成目標。", trialPrice: "320", regularPrice: "580", packageDetails: "12堂套餐 $6,000", ageGroups: ["成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/22.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_23", name: "區俊文", sportsCategory: "空手道", location: "新蒲崗", bio: "WKF認可空手道黑帶四段教練，前亞洲區賽事代表。提供個人及小組訓練，強調正確技術及安全性。歡迎無經驗學員，亦提供晉段考試備考指導。", trialPrice: "200", regularPrice: "380", packageDetails: "10堂套餐 $3,200", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/23.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_24", name: "鄧雪儀", sportsCategory: "普拉提", location: "尖沙咀", bio: "Balanced Body認可普拉提教練，擁有10年教學經驗。善用Reformer、Cadillac及Wunda Chair等器械協助學員改善脊椎問題及體態。歡迎物理治療後康復學員。", trialPrice: "400", regularPrice: "680", packageDetails: "器械普拉提月費（8堂）$4,800", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/24.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_25", name: "雷浩然", sportsCategory: "籃球", location: "大圍", bio: "FIBA Level 2認可教練，曾帶隊參加全港學界籃球邀請賽。提供技術訓練（控球、投籃、防守步法）及戰術分析課程，適合U12至U19青少年學員。", trialPrice: "280", regularPrice: "480", packageDetails: "暑期訓練營（20堂）$7,000", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/25.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_26", name: "廖詩琪", sportsCategory: "舞蹈", location: "紅磡", bio: "香港中文大學文化管理系（主修舞蹈藝術）畢業。提供K-Pop舞蹈、現代爵士舞及Hip Hop課程，歡迎完全零基礎學員，以享受舞蹈為主要教學理念。", trialPrice: "200", regularPrice: "380", packageDetails: "8堂入門課程 $2,600", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/26.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_27", name: "莫建明", sportsCategory: "游泳", location: "天水圍", bio: "香港業餘游泳總會認可教練，服務超過800位學員。提供成人學游泳課程，以循序漸進的方式幫助怕水成人建立信心。課程於室內暖水池進行，全年均可報名。", trialPrice: "150", regularPrice: "300", packageDetails: "成人學游泳（12堂）$3,000", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/27.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_28", name: "方惠婷", sportsCategory: "羽毛球", location: "樂富", bio: "香港羽毛球總會認可教練，前香港大學校隊主力。擅長女子單打技術指導及步法訓練。提供個人及雙打搭配訓練，歡迎業餘球員提升技術水平。", trialPrice: "220", regularPrice: "400", packageDetails: "雙打培訓套餐（8堂，兩人計）$2,800", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/28.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_29", name: "謝天明", sportsCategory: "拳擊", location: "長沙灣", bio: "WBC認可拳擊教練，曾培育多位香港青年拳擊代表。提供初學者基礎班及進階技術訓練，特別設有女性自衛訓練班。強調拳擊作為體能訓練工具，不限於格鬥目的。", trialPrice: "180", regularPrice: "380", packageDetails: "健身拳擊班（8堂）$2,400", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/29.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_30", name: "顏嘉琳", sportsCategory: "網球", location: "南區", bio: "ITF Level 1認可教練，主要服務南區及港島居民。善用影像分析協助學員改進技術動作。提供小組班（最多4人）及私人課程，適合7歲以上學員。", trialPrice: "250", regularPrice: "450", packageDetails: "家庭套餐（大人+小童各4堂）$3,200", ageGroups: ["兒童（12歲以下）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/30.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_31", name: "連志豪", sportsCategory: "足球", location: "上水", bio: "香港足球總會B級教練，現為地區足球學校校長。多年社區足球推廣工作，課程重視愛護隊友、尊重對手的體育精神，設有暑期密集訓練班。", trialPrice: "200", regularPrice: "380", packageDetails: "暑期訓練班（20堂）$5,500", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/31.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_32", name: "施詩敏", sportsCategory: "游泳", location: "石硤尾", bio: "專注協助有特殊學習需要（SEN）兒童的游泳教練，獲香港復康會認可。以高耐心及個別化教學方式，幫助不同能力的孩子享受水上運動，建立自信心。", trialPrice: "250", regularPrice: "500", packageDetails: "SEN兒童游泳課（12堂）$5,000", ageGroups: ["兒童（12歲以下）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/32.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_33", name: "龔俊傑", sportsCategory: "田徑", location: "彩虹", bio: "ACSM認證運動生理學家兼私人教練，擁有運動醫學碩士學位。專注慢性病患者（如糖尿病、高血壓）的安全運動訓練及體重管理，所有課程均提供詳細健康追蹤記錄。", trialPrice: "280", regularPrice: "550", packageDetails: "健康管理計劃（16堂+膳食諮詢）$8,000", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/33.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_34", name: "卓珮珊", sportsCategory: "瑜伽", location: "寶琳", bio: "Sivananda瑜伽認證導師，熟習多派瑜伽傳統。提供個人靜修式課程，結合冥想、呼吸法及體位法，特別適合工作壓力大、睡眠質素差的都市人。", trialPrice: "200", regularPrice: "400", packageDetails: "身心靜修計劃（8週，每週一堂）$2,800", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/34.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_35", name: "蘇立文", sportsCategory: "游泳", location: "屯門", bio: "教齡逾20年的資深游泳教練，曾任香港游泳代表隊助理教練。現專注成人及長者游泳訓練，提供水中有氧運動課程，對關節有益且運動風險低。", trialPrice: "180", regularPrice: "350", packageDetails: "長者水中有氧班（月費，每週兩次）$1,800", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/35.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_36", name: "余嘉敏", sportsCategory: "舞蹈", location: "西九龍", bio: "香港芭蕾舞學校訓練出身，曾於英國及美國進修。提供古典芭蕾、當代舞及儀態訓練，尤其擅長協助成人（含零基礎）以成熟心態學習芭蕾，強調享受過程多於技術完美。", trialPrice: "280", regularPrice: "500", packageDetails: "成人芭蕾入門（10堂）$4,200", ageGroups: ["成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/36.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_37", name: "麥國輝", sportsCategory: "乒乓球", location: "荔枝角", bio: "前全港乒乓球公開賽甲組季軍，持有中國乒乓球協會B級教練資格。提供個人及雙打技術訓練，擅長分析學員的發球、接球及反手技術。", trialPrice: "200", regularPrice: "380", packageDetails: "雙打組合培訓（8堂，兩人計）$2,600", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/37.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_38", name: "黎嘉怡", sportsCategory: "普拉提", location: "跑馬地", bio: "Peak Pilates認證教練，曾赴澳洲完成進修。提供舞者和運動員的功能性普拉提訓練，協助改善表現及預防傷患，同時設有一般大眾的體態改善課程。", trialPrice: "380", regularPrice: "650", packageDetails: "運動員訓練計劃（12堂）$6,600", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/38.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_39", name: "冼子健", sportsCategory: "足球", location: "葵涌", bio: "亞足聯B級教練，熟悉小場地五人足球（Futsal）訓練。提供室內足球技術精練課程，特別適合未有場地限制的市區居民。設有成人夜間班及假日青少年班。", trialPrice: "220", regularPrice: "400", packageDetails: "Futsal技術班（10堂）$3,200", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/39.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_40", name: "蕭慧茵", sportsCategory: "瑜伽", location: "將軍澳", bio: "Iyengar Yoga認證導師，善用輔助工具（繩、磚、毯）幫助學員達到正確體位。特別適合有舊患或身體限制的人士，以細心觀察及個別調整見稱。", trialPrice: "220", regularPrice: "420", packageDetails: "Iyengar入門課程（8堂）$2,900", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/40.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_41", name: "梁志峰", sportsCategory: "劍擊", location: "柴灣", bio: "前亞洲青年劍擊錦標賽香港代表，擅長重劍及佩劍。現為多所中學劍擊隊主教練，熟悉學界比賽規則，提供賽前技術及體能強化訓練。", trialPrice: "320", regularPrice: "550", packageDetails: "學界備賽套餐（12堂）$5,400", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/41.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_42", name: "鄺美琪", sportsCategory: "田徑", location: "薄扶林", bio: "ISSA認證私人教練及營養顧問。提供整合式訓練計劃，結合重量訓練、HIIT及彈力帶訓練，配合個人化餐單建議，適合希望全方位改善體態的學員。", trialPrice: "300", regularPrice: "550", packageDetails: "12週身體重塑計劃 $5,500", ageGroups: ["成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/42.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_43", name: "甘俊賢", sportsCategory: "高爾夫球", location: "清水灣", bio: "前香港高爾夫球公開賽業餘組冠軍，持有USGTF教練資格。擅長利用科技輔助（Trackman彈道分析儀）精準評估學員表現，致力將複雜技術以淺白易懂的語言傳授。", trialPrice: "550", regularPrice: "900", packageDetails: "Trackman全面分析套餐（6堂）$4,800", ageGroups: ["成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/43.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_44", name: "趙詠珊", sportsCategory: "排球", location: "沙田", bio: "前香港女子排球甲組聯賽球員，現任多所中學排球隊顧問教練。善於發掘學員潛能，提供由基礎至進階的全面訓練，包括扣球、攔網及戰術走位等技術。", trialPrice: "200", regularPrice: "400", packageDetails: "小組技術班（6人，10堂）每位$1,500", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/44.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_45", name: "藍偉傑", sportsCategory: "跆拳道", location: "東涌", bio: "WTF跆拳道黑帶四段，前香港代表隊教練組成員。提供正規品勢及競技對打訓練，設有兒童及成人獨立班組，強調紀律與自我保護意識。", trialPrice: "200", regularPrice: "380", packageDetails: "競技班月費（每週兩次）$1,600", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/45.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_46", name: "文嘉儀", sportsCategory: "普拉提", location: "跑馬地", bio: "BASI認可普拉提教練，曾於倫敦完成訓練。主力提供孕婦普拉提及產後復康課程，對準媽媽的身體狀況有深入了解，以安全及有效的動作減輕孕期不適。", trialPrice: "420", regularPrice: "700", packageDetails: "孕婦普拉提套餐（8堂）$4,800", ageGroups: ["成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/46.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_47", name: "林俊生", sportsCategory: "跑步", location: "西貢", bio: "前越野跑港隊成員，完成多項超級馬拉松賽事（包括UTMB 100英里）。提供越野跑技術訓練及備賽計劃，熟悉西貢郊野公園路線，適合愛好大自然的跑手。", trialPrice: "200", regularPrice: "420", packageDetails: "越野跑訓練計劃（12週）$4,200", ageGroups: ["成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/47.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_48", name: "阮文正", sportsCategory: "高爾夫球", location: "深水灣", bio: "前職業高爾夫球巡迴賽球員，轉型教練後屢獲好評。提供全面揮棒技術分析，適合認真改善差點的中進階球員。", trialPrice: "600", regularPrice: "1000", packageDetails: null, ageGroups: ["成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/48.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_49", name: "黎家怡", sportsCategory: "游泳", location: "大嶼山", bio: "香港游泳代表隊前成員，擁有豐富的競技游泳訓練經驗。現提供個人化游泳課程，專注四式技術精進及競賽備戰，適合有志參加香港學界或業餘賽事的學員。", trialPrice: "300", regularPrice: "550", packageDetails: "競技訓練（12堂）$5,500", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/49.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_user_50", name: "何碧珊", sportsCategory: "瑜伽", location: "香港仔", bio: "資深瑜伽導師，教齡超過15年，持Yoga Alliance RYT-500資格。擅長Yin Yang結合課程，以陰瑜伽平衡和陽瑜伽強化，提供適合各層次學員的個人化指導。", trialPrice: "220", regularPrice: "420", packageDetails: "月費班（8堂）$2,800", ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/50.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_athletics_1", name: "陳志強", sportsCategory: "田徑", location: "沙田運動場", bio: "香港田徑代表隊前成員，專注短跑及跨欄訓練，擁有超過10年教練經驗，曾培訓多名全港運動會獎牌得主。", trialPrice: "350", regularPrice: "600", packageDetails: "10堂套餐 $5000", ageGroups: ["青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/51.jpg", whatsappNumber: "85291234567" },
  { userId: "seed_athletics_2", name: "林美琪", sportsCategory: "田徑", location: "將軍澳運動場", bio: "前亞洲田徑錦標賽參賽選手，專注長跑及馬拉松訓練，提供個人化訓練計劃，適合備戰比賽或改善個人最佳成績的跑手。", trialPrice: "300", regularPrice: "550", packageDetails: null, ageGroups: ["成人（18歲以上）", "長者（60歲以上）"], teachingFocus: ["競賽", "興趣"], experienceLevel: "職業運動員", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/women/51.jpg", whatsappNumber: "85298765432" },
  { userId: "seed_athletics_3", name: "黃俊傑", sportsCategory: "田徑", location: "維多利亞公園", bio: "香港業餘田徑總會認可教練，主力教授投擲及跳遠項目，教學風格輕鬆且富成效，適合學校運動員及業餘愛好者。", trialPrice: "280", regularPrice: "500", packageDetails: "8堂套餐 $3500", ageGroups: ["兒童（12歲以下）", "青少年（12-17歲）", "成人（18歲以上）"], teachingFocus: ["興趣"], experienceLevel: "持牌教練", isFeatured: false, isApproved: true, profileImageUrl: "https://randomuser.me/api/portraits/men/52.jpg", whatsappNumber: "85267891234" },
];

const reviews = [
  { coachId: 1, userId: "reviewer_1", userName: "陳小明", rating: 5, comment: "陳教練非常專業，我家小孩只上了8堂就能獨立游泳了！", isApproved: true },
  { coachId: 1, userId: "reviewer_2", userName: "李雪梅", rating: 4, comment: "教學方法很有系統，十分推薦。", isApproved: true },
  { coachId: 2, userId: "reviewer_3", userName: "張美儀", rating: 5, comment: "李老師的瑜伽課讓我壓力全消，每次下課都感覺輕鬆很多。", isApproved: true },
  { coachId: 3, userId: "reviewer_4", userName: "劉小威", rating: 5, comment: "張教練很有熱誠，訓練很紮實，我的控球明顯進步了。", isApproved: true },
  { coachId: 4, userId: "reviewer_5", userName: "王嘉樂", rating: 4, comment: "黃教練非常認真，會用影片分析我的技術，效果顯著。", isApproved: true },
  { coachId: 5, userId: "reviewer_6", userName: "鄧浩賢", rating: 5, comment: "吳教練讓我對拳擊有全新的認識，訓練既安全又有效。", isApproved: true },
  { coachId: 6, userId: "reviewer_7", userName: "何穎珊", rating: 5, comment: "林老師的普拉提課幫我解決了長期背痛問題，非常感謝！", isApproved: true },
  { coachId: 7, userId: "reviewer_8", userName: "方志峰", rating: 4, comment: "鄭教練對小朋友很有耐心，我兒子很喜歡上他的課。", isApproved: true },
  { coachId: 11, userId: "reviewer_9", userName: "馬俊生", rating: 5, comment: "梁教練的分析非常到位，我的差點由18降到14，很高興！", isApproved: true },
  { coachId: 17, userId: "reviewer_10", userName: "黃子軒", rating: 5, comment: "葉教練的訓練計劃很個人化，我在3個月內減了12磅且肌肉明顯增加。", isApproved: true },
];

export async function seedIfEmpty() {
  try {
    const result = await db.select({ total: count() }).from(coachesTable);
    const total = result[0]?.total ?? 0;

    if (total > 0) {
      logger.info({ total }, "Database already has coaches, skipping seed");
      return;
    }

    logger.info("Database is empty — seeding sample coaches...");
    const coachesWithAchievements = coaches.map(c => {
      const isPro = c.experienceLevel?.includes("職業") || c.experienceLevel?.includes("專業運動員");
      const sport = c.sportsCategory;
      return {
        ...c,
        teachingAchievements: c.teachingAchievements ??
          `執教${sport}超過5年，累計指導逾200名學員。曾任職本地學校及體育會教練，多位學員於校際及公開賽事中獲獎。教學風格因材施教，注重基本功及運動安全。`,
        sportsAchievements: c.sportsAchievements ?? (isPro
          ? `前香港${sport}代表隊成員，曾參與多項國際及亞洲區賽事。本地公開賽多次獲得獎項，並擁有多年高水平比賽經驗。`
          : `本地${sport}愛好者及持證教練，曾參與多項本地賽事並取得不俗成績。持續進修以掌握最新的訓練方法及運動科學知識。`),
      };
    });
    const inserted = await db.insert(coachesTable).values(coachesWithAchievements).returning({ id: coachesTable.id });
    logger.info({ count: inserted.length }, "Coaches seeded successfully");

    const reviewsWithRealIds = reviews.map(r => ({
      ...r,
      coachId: inserted[r.coachId - 1]?.id ?? inserted[0].id,
    }));
    await db.insert(reviewsTable).values(reviewsWithRealIds);
    logger.info({ count: reviewsWithRealIds.length }, "Reviews seeded successfully");
  } catch (err) {
    logger.error({ err }, "Seed failed — continuing startup anyway");
  }
}
